version: '3'
services:
  front:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./front:/app
      - ./back:/back
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./back:/app